name: build
on:
  push:
jobs:
  compile:
    name: compile asm files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker run -v "$PWD":/workspace micheldebree/kickass src/test.asm   