name: build
on:
  push:
jobs:
  compile:
    name: compile asm files
    runs-on: ubuntu-latest
    steps:
    - name: compile it
      run: docker run -v "$PWD":/workspace micheldebree/kickass src/test.asm   