name: build
on:
  push:
jobs:
  compile:
    name: compile asm files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker run -v "$PWD":/workspace micheldebree/kickass src/test.asm
    - run: |
        git config --global user.name 'GitHub Actions Workflow'
        git config --global user.email 'githubactions@users.noreply.github.com'
        git add src/test.prg
        git commit -m "add test.prg"
        git push